music/urls.py
from django.conf.urls import url  # include
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.login_user, name='login_user'),
    url(r'^albums/$', views.index, name='index'),
    url(r'^favorite-songs/$', views.all_favorite_songs, name='all_favorite_songs'),
    url(r'^(?P<album_id>[0-9]+)/details/$', views.details, name='details'),
    url(r'^all-songs/$', views.all_songs, name='all_songs'),
    url(r'^(?P<album_id>[0-9]+)/delete-album/$', views.delete_album, name='delete_album'),
    url(r'^(?P<album_id>[0-9]+)/favorite-album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<song_id>[0-9]+)/favorite-song/$', views.favorite_song, name='favorite_song'),
    url(r'^(?P<song_id>[0-9]+)/delete-song/$', views.delete_song, name='delete_song'),
    url(r'^(?P<song_id>[0-9]+)/delete-song/$', views.delete_song, name='delete_song'),
    url(r'^logout-user/$', views.logout_user, name='logout_user'),
]

musicapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static

# import music

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=255)
    album_title = models.CharField(max_length=255)
    genre = models.CharField(max_length=255)
    album_logo = models.FileField()
    isfavorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + '-' + self.artist


class Songs(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=255)
    audio_file = models.FileField()
    isfavorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms


class AlbumForm(forms.Form):
    pass

music/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
# , get_list_or_404
from .models import Album, Songs
from django.db.models import Q
# from django.shortcuts import redirect
# from django.core.urlresolveers import reverse


def search_songs(songs, query):
    songs = songs.filter( Q(song_title__icontains = query))
    return songs
	 

def login_user(request):
    if request.POST or request.GET:
        return redirect('music:index')
    return render(request, 'music/login_user.html')


def index(request):
    albums = Album.objects.all()
    query = request.GET.get("query")
    if query:
        albums = albums.filter(
            Q(album_title__icontains=query) |
            Q(artist__icontains=query)
        )
    return render(request, 'music/index.html', {'albums': albums})


def details(request, album_id):
    album = Album.objects.get(pk=album_id)
    songs = album.songs_set.all()
    query = request.GET.get('query')
    if query:
        songs = search_songs(songs,query)
    return render(request, 'music/details.html', {'songs': songs, 'album': album})


def all_songs(request):
    songs = Songs.objects.all()
    query = request.GET.get('query')
    if query:
        songs = search_songs(songs,query)
    return render(request, 'music/all_songs.html', {'songs': songs})


def all_favorite_songs(request):
    songs = Songs.objects.filter(isfavorite=1)
    query = request.GET.get('query')
    if query:
        songs = search_songs(songs,query)
    return render(request, 'music/all_favorite_songs.html', {'songs': songs})


def delete_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    album.delete()
    return redirect('music:index')
    # return render(request, 'music/index.html')


def delete_song(request, song_id):
    song = get_object_or_404(Songs, pk=song_id)
    album_id = song.album.id
    song.delete()
    previous_url = request.META.get('HTTP_REFERER')
    if previous_url:
        return redirect(previous_url)
    return redirect('music:details', album_id)


def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    album.isfavorite = not album.isfavorite
    album.save()
    return redirect('music:index')
    # return render(request, 'music/index.html')


def favorite_song(request, song_id):
    song = get_object_or_404(Songs, pk=song_id)
    song.isfavorite = not song.isfavorite
    song.save()
    previous_url = request.META.get('HTTP_REFERER')
    if previous_url:
        return redirect(previous_url)
    args = (song.album.id,)
    return redirect('music:details', *args)


def home(request):
    return HttpResponse('this is home page')


def logout_user(request):
    pass

music/templates/music/all_favorite_songs.html
{% extends 'music/base_details.html' %}
{% block all_favorite_songs_active  %}active{% endblock %}
{% block title %} Favorite songs {% endblock %}
{% block details_heading %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div>
            <h2>Favorite Songs</h2>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/all_songs.html
{% extends 'music/base_details.html'%}
{% block songs_active %}active{% endblock %}
{% block details_heading %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div>
            <h2>All Songs</h2>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'music/favicon.ico' %}"/>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!--  for creative fonrs from googleapis-->
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <!--  user defined style sheet should always be after bootstrap style sheet-->
    <link rel="stylesheet" href="{% static 'music/css/style.css' %}"/>
    {% block extra_head %}{% endblock %}


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- user defined js -->
    <script src="{% static 'music/js/main.js' %}"></script>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'music:index'%}" style="font-family:Lobster,cursive;color:#f18989;" color="red">R's Music Collection</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav">
            <li class="{% block album_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd"></span>&nbsp; Albums</a></li>
            <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:all_songs'%}"><span class="glyphicon glyphicon-music"></span>&nbsp; Songs</a></li>
            <li class="{% block all_favorite_songs_active %}{% endblock %}"><a href="{% url 'music:all_favorite_songs'%}"><span class="glyphicon glyphicon-heart"></span>&nbsp; Favorite Songs</a></li>
          </ul>
          <form class="navbar-form navbar-left" action="#" role="search">
            <div class="form-group">
              <input type="text" class="form-control" name="query" placeholder="Search">
            </div>
            {% csrf_token %}
            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              <li class="active" class="dropdown"><a data-toggle="dropdown" aria-expanded="false" href="#" class="dropdown-toggle"><span class="glyphicon glyphicon-user"></span>&nbsp; {{request.user}} <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                      <li role="presentation"><a href="#">Profile</a></li>
                      <li role="presentation"><a href="#">Settings</a></li>
                  </ul>
              </li>
              <li class=""><a href="#"><span class="glyphicon glyphicon-off">&nbsp;</span></a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
{% block body %}{% endblock %}
  </body>
</html>

music/templates/music/base_details.html
{% extends 'music/base.html' %}
{% block title %}Songs{% endblock %}
{% block body %}
<div class="albums-container container-fluid">
{% block details_heading %}{% endblock %}

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Play/Pause </th>
                    <th>Song </th>
                    <th>Type</th>
                    <th>Favorite </th>
		    <th>Delete </th>
                </tr>
            </thead>
            <tbody>
            {% for song in songs %}
                <tr>
                    <td style="height:72px;width:378px;">
                        <audio controls>
                            <source src="{{song.audio_file.url}}" type="audio/ogg"></source>
                            <source src="{{song.audio_file.url}}" type="audio/mpeg"></source>
                            Your browser does not support the audio element.
                        </audio>
                    </td>
                    <td>{{song.song_title}}</td>
                    <td>mp3</td>
                    <td><a href="{% url 'music:favorite_song' song.id %}"><i class="glyphicon glyphicon-heart{% if not song.isfavorite %}-empty{% endif %}"></i></a></td>
                    <td><a href="{% url 'music:delete_song' song.id %}"><i class="glyphicon glyphicon-trash"></i></a></td>
		</tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


</div>
{% endblock %}

music/templates/music/details.html
{% extends 'music/base_details.html'%}
{% block songs_active %}active{% endblock %}
{% block details_heading %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div>
            <h2>Ablum - {{album.album_title}}</h2>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}Albums{% endblock %}
{% block album_active %}active{% endblock %}
{% block body %}
<div class="albums-container container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div>
                <h2>{{request.user}}'s Ablums</h2>
            </div>
        </div>
    </div>


        <div class="row">
            {% if albums%}
            {% for album in albums %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 ">
                <div class="thumbnail"><a href="{% url 'music:details' album.id %}"><img src="{{album.album_logo.url}}"  style="min-height:200px;height:200px;" class="img-rounded img-responsive" /></a>
                    <div class="caption">
                        <h3 class="text-center" style="color:rgb(224,135,135);">{{album.album_title}}</h3>
                        <div class="row">
                            <div class="col-md-5 col-sm-12">
                                <a class="btn btn-default btn-block" role="button" href="{% url 'music:favorite_album' album.id %}">favorite <i class="glyphicon glyphicon-heart{% if not album.isfavorite %}-empty{% endif %}"></i></a>
                            </div>
                            <div class="col-md-4 col-sm-12"><a class="btn btn-default btn-block" role="button" href="{% url 'music:details' album.id %}">View </a></div>
                            <div class="col-md-3 col-sm-12">
                                <form method="post" action="{% url 'music:delete_album' album.id %}" class="form-inline" >
                                    <input type="hidden" name="album_id" value="{{ album.id }}" class="form-control" />
                                    {% csrf_token %}
                                    <button class="btn btn-default btn-block" type="submit"> <i class="glyphicon glyphicon-trash"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>


</div>
{% endblock %}

music/templates/music/login_user.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'music/css/Footer-Dark.css'%}">
    <link rel="stylesheet" href="{% static 'music/css/Login-Form-Clean.css'%}">
    <link rel="stylesheet" href="{% static 'music/css/Login-Form-Dark.css'%}">
    <link rel="stylesheet" href="{% static 'music/css/Registration-Form-with-Photo.css'%}">
    <link rel="stylesheet" href="{% static 'music/css/styles.css'%}">
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'music:login_user'%}" style="font-family:Lobster,cursive;color:#f18989;" color="red">Rohith Reddy's Music Collection</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar">
                <form class="navbar-form navbar-right" method="get">
                    <div class="form-group">
                        <input class="form-control" type="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit" style="background-image:url(&quot;None&quot;);background-color:rgb(244,71,107);">Log In</button>
                    </div>
                </form>
                <form class="navbar-form navbar-right" method="get">
                    <input type="hidden" name="guestuser" />
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit" style="background-image:url(&quot;None&quot;);background-color:rgb(244,71,107);">Guest user</button>
                    </div>
                </form>
            </div>
        </div>
    </nav>
    <div class="register-photo" style="background-image:url(&quot;{%static 'music/images/star-sky.jpg'%}&quot;);background-position:center;">
        <div class="form-container">
            <div class="image-holder" style="background-image:url(&quot;{%static 'music/images/Music-Industry-Photo.jpg'%}&quot;);"></div>
            <form method="post">
                {% csrf_token %}
                <h2 class="text-center"><strong>Create</strong> an account.</h2>
                <div class="form-group">
                    <input class="form-control" type="text" name="username" placeholder="User name">
                </div>
                <div class="form-group">
                    <input class="form-control" type="email" name="email" placeholder="Email">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password-repeat" placeholder="Password (repeat)">
                </div>
                <!-- <div class="form-group">
                    <div class="checkbox">
                        <label class="control-label">
                            <input type="checkbox">I have only single account.</label>
                    </div>
                </div> -->
                <div class="form-group">
                    <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
                </div>
            </form>
        </div>
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-4 item social"><a href="https://www.facebook.com/rohithreddykota"><i class="icon ion-social-facebook"></i></a><a href="https://twitter.com/rohithreddykota"><i class="icon ion-social-twitter"></i></a><a href="https://github.com/rohithreddykota"><i class="icon ion-social-github"></i></a><a href="https://www.instagram.com/rohithreddykota/"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Rohith Reddy Kota © 2017</p>
            </div>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>